NexusMutual/sdk

contracts-metadata/contracts.json

Step 1/2 to update the list of supported products. 
Step 2/2 is here: https://github.com/NexusMutual/frontend-react/pull/607
Note: I've copy-pasted the json from frontend, hence the extra linting changes. 
Note 2: Once merged, this has to be manually deployed, and only then the frontend PR can be merged.

Feat: update the list of supported products

---

contracts-metadata/contracts.json

Step 2 > https://github.com/NexusMutual/frontend-react/pull/635
See https://github.com/NexusMutual/frontend-react/issues/634

feat: delist babylon finance

---

contracts-metadata/contracts.json
contracts-metadata/images/gmx.svg

Step 2 > https://github.com/NexusMutual/frontend-react/pull/636
See https://github.com/NexusMutual/frontend-react/issues/633

feat: added gmx contract details for listing

---

contracts-metadata/contracts.json

Step 2: https://github.com/NexusMutual/frontend-react/pull/639
See [#638](https://github.com/NexusMutual/frontend-react/issues/638)

feat: added more supported chains to the specified protocols

---

contracts-metadata/contracts.json

For more info, see Slack discussion: https://nexusmutual.slack.com/archives/G010M0U3BT8/p1665584291260019
This should go 1st before https://github.com/NexusMutual/frontend-react/pull/672

Delisting Celsius, BlockFi, Nexo, inLock, Ledn and Yield.app

---

contracts-metadata/contracts.json

To be merged before https://github.com/NexusMutual/frontend-react/pull/708

Delist Gemini

---

contracts-metadata/contracts.json

To be merged after https://github.com/NexusMutual/frontend-react/pull/712

Feat: delists

---

package-lock.json
package.json
scripts/build.js

Sherlock and Stakewise products types got reversed when added on chain. This PR adds an exception when generating the products list to fix this issue.

Swap sherlock and stakewise products types

---

package-lock.json
package.json

Bump version to 0.0.12

---

package-lock.json
package.json
scripts/build-logos.js

This way `frontend-react`'s pipeline is a lot nicer. Not the best solution, but works for now 👍

Add some formatting magic to build-logos.js

---

package-lock.json
package.json

Bump deployments package to get latest changes for abi type safety.

Bump deployments package

---

package-lock.json
package.json
src/quote/getQuoteAndBuyCoverInputs.test.ts
src/quote/getQuoteAndBuyCoverInputs.ts
src/types/cover.ts
src/types/data.ts

Closes #113 
Return the user what is the maxCapacity on "Not enough capacity" error
* add unit tests

feat: Add capacity error data not enough capacity

---

.eslintrc
.husky/pre-push
package-lock.json
package.json
public/scripts/copy-logos.cjs
scripts/build-logos.js
scripts/build-products.js
scripts/build.js
scripts/bump-version.js
src/index.ts
src/quote/getQuoteAndBuyCoverInputs.test.ts
src/quote/getQuoteAndBuyCoverInputs.ts
src/swap/calculateEthForExactNxm.test.ts
src/swap/calculateEthForExactNxm.ts
src/swap/calculateExactEthForNxm.test.ts
src/swap/calculateExactEthForNxm.ts
src/swap/calculateExactNxmForEth.test.ts
src/swap/calculateExactNxmForEth.ts
src/swap/calculateNxmForExactEth.test.ts
src/swap/calculateNxmForExactEth.ts
src/swap/calculatePriceImpactA.test.ts
src/swap/calculatePriceImpactA.ts
src/swap/calculatePriceImpactB.test.ts
src/swap/calculatePriceImpactB.ts
src/swap/calculateSpotPrice.test.ts
src/swap/index.ts
src/types/api.ts
src/types/cover.ts

Closes #112 
Fix linting issues and adjust .eslint rules
Fix linting issues and adjust .eslint rules
all existing tests should still pass

chore: Fix linting

---

package-lock.json
package.json
src/quote/getQuoteAndBuyCoverInputs.test.ts
src/quote/getQuoteAndBuyCoverInputs.ts
src/types/cover.ts

https://github.com/NexusMutual/sdk/issues/125
* fix display.maxCapacity
* added unit test

Fix displayInfo.maxCapacity

---

package-lock.json
package.json
src/types/cover.ts

Add category types for the categories filter on the browse cover page.
Related to #541

Add product categories

---

package-lock.json
package.json

New version of contracts were deployed
Bump `@nexusmutual/deployments` to 2.6.0
N/A

chore: Bump`@nexusmutual/deployments` to 2.6.0

---

package-lock.json
package.json
scripts/utils.js
src/constants/buyCover.ts
src/constants/products.ts

Add USDC support
- Add USDC to cover asset
- Add a function to calculate cover assets bit mapping for adding/editing products 
Please describe the tests cases that you ran to verify your changes. Add further instructions on 
how to run them if needed (i.e. migration / deployment scripts, env vars, etc).

feat: usdc support

---

.github/ISSUE_TEMPLATE/product-listing-template.md
.github/ISSUE_TEMPLATE/product-type-listing-template.md

We're moving listing requests from the frontend-react repo to the sdk repo.

Add issue templates for product / product type listings

---

.github/ISSUE_TEMPLATE/product-listing-request.md
.github/ISSUE_TEMPLATE/product-type-listing-request.md

Update the template so that requester fills in the spreadsheet directly
added instructions to fill in spreadsheet and modified template sections accordingly
* product-listing-request
* product-type-listing-request
N/A

chore: Update product/product type listing templates

---

package-lock.json
package.json
scripts/build-products.js
scripts/list-product-types.js
scripts/list-products.js

Issue: #150 
Add CoverProducts support for building sdk and fetching all the data for products and productTypes
Please describe the tests cases that you ran to verify your changes. Add further instructions on 
how to run them if needed (i.e. migration / deployment scripts, env vars, etc).

feat: Add support for CoverProducts

---

package.json
scripts/build-products.js

Include relevant motivation and context. A link to the issue is enough if it contains all the relevant 
information.
Include a summary of the change.
Please describe the tests cases that you ran to verify your changes. Add further instructions on 
how to run them if needed (i.e. migration / deployment scripts, env vars, etc).

Fix: metadata timestamp type and product type fetching

---

data/legacy-product-metadata.json
package-lock.json
package.json
scripts/build-products.js

Issue: #175 
- Cache metadata from the old cover contract
- Add event filter for the Cover Products contract for the products and their metadata
N/A

Fix: build products script

---

.github/ISSUE_TEMPLATE/product-listing-request.md
.github/ISSUE_TEMPLATE/product-type-listing-request.md

Update listing request templates to include engineering checklist
* add engineering checklist to listing templates

chore: Update listing request templates

---

package-lock.json
package.json

Update `@nexusmutual/deployments` to 2.8.0
* Update `@nexusmutual/deployments` to 2.8.0
* Update version to 0.4.8
@next -rc1 FE e2e testing

 chore: Update @nexusmutual/deployments to 2.8.0

---

package-lock.json
package.json

Include relevant motivation and context. A link to the issue is enough if it contains all the relevant 
information.
Include a summary of the change.
Please describe the tests cases that you ran to verify your changes. Add further instructions on 
how to run them if needed (i.e. migration / deployment scripts, env vars, etc).

Bump package version to 0.4.9

---

package-lock.json
package.json
scripts/build-products.js
scripts/utils.js

Replaces the hardcoded coverAssets mapping with dynamically reading latest coverAssets data on-chain
ran `nr build` and manually verified generated products.json

feat: add read of latest coverAssets on-chain

---

package-lock.json
package.json
scripts/build-products.js
scripts/utils.js

* add cbBTC coverAsset support
* Replaces the hardcoded coverAssets mapping with dynamically reading latest coverAssets data on-chain
ran `nr build` and checked product.json

feat: add cbBTC coverAsset support

---

package-lock.json
package.json

update @nexusmutual deployments package 2.10.1
NA

chore: update @nexusmutual deployments package 2.10.1

---

.github/workflows/merge-master.yml
package-lock.json

Tweaks workflow file to be able to read the env secret.

chore: add production env to ci workflow

---

package-lock.json
package.json

chore: bump version to v0.6.1

---

package-lock.json
package.json
scripts/build-products.js

Support for https://github.com/NexusMutual/frontend-next/issues/1257
- `npm run build` - check products json objects to contain `minPrice` (100 = 1%)
- yield token products have `minPrice` set as `0` (they're deprecated)

feat: add product min price

---

.github/workflows/merge-master.yml
.github/workflows/pull-request.yml

chore: disable ts:check and circular dependency

---

.github/workflows/merge-master.yml

add missing --ignore-scripts flag on npm publish

ci: add missing --ignore-scripts flag on npm publish

---

.github/workflows/merge-master.yml

* https://github.com/NexusMutual/sdk/pull/285
* https://github.com/NexusMutual/sdk/issues/280
* https://github.com/NexusMutual/sdk/pull/283

Release 0.7.1

---

.github/workflows/merge-master.yml

add Remove prepare script step

ci: add Remove prepare script step

---

package-lock.json
package.json
src/constants/privateProducts.js

Prep for https://github.com/NexusMutual/sdk/issues/305#issuecomment-2659000008
- -

feat: make nexus cover products public

---

package-lock.json
package.json

Update @nexusmutual/deployments package to latest version

chore: deployments package 2.11.1

---

package-lock.json
package.json
src/constants/privateProducts.js
src/logos/273-l1.svg

https://github.com/NexusMutual/sdk/issues/311
- -

feat: add new listing logo

---

ON_CHAIN_UPDATES.md

This PR introduces a new doc file to help us trigger the sdk build when there are on-chain updates not requiring code changes. Updating this doc with a simple log of the change will help trigger our new release flow and get the latest on-chain updates.
- N/A

feat: added new cover wording update for Native Syndicate Cover

---

package-lock.json
package.json
scripts/build-products.js
src/types/ipfs.ts

chore: update deployments package v2.12.0

---

.github/workflows/release-next.yml
.github/workflows/release.yml

* release-next
* use determine-rc-version workflow
* release
* use feat prefix for branch and commit type for frontend repos 
NOTE: [this PR](https://github.com/NexusMutual/workflows/pull/8) must be merged first 

chore: ci workflows improvements

---

package-lock.json
package.json

chore: update @nexusmutual/deployments to v2.12.2

---

public/index.html

chore: mark limit orders contract as proxy

---

ON_CHAIN_UPDATES.md

https://github.com/NexusMutual/sdk/issues/377
- check Fasanara (productId =250) annex

fix: update Fasanara listing annex

---

.github/ISSUE_TEMPLATE/product-listing-request.md
.github/workflows/release.yml

- workers repo needs to be up to date with the latest listings
- -

chore: add workers repo in bump PRs list

---

README.md

chore: update the docs with breaking changes
