- package-lock.json
- package.json
- scripts/build.js
We got the events in the wrong order so the sdk picked up the first ones instead of the latest. 
This PR fixes this by sorting the logs in descending order to get the latest events data.
> Fix: products ipfs data latest updates

- package-lock.json
- package.json
- scripts/build.js
Sherlock and Stakewise products have been deprecated so we no longer need to correct their product types in the sdk output.
> Chore: remove exception for sherlock and stakewise after deprecation

- package-lock.json
- package.json
- scripts/build-logos.js
- scripts/build.js
- src/index.ts
Something in the svg to component setup was causing tree shaking to be broken. It was probably the Babel output. The output did contain `/* PURE */` comments, but for probably some reason—which I don't have enough knowledge for—it still broke.
Since we did not use the component versions of the svg's I decided to remove the logic for now. If we ever need it back, we can check history or get it from the (deprecated) `@nexusmutual/logos` repo.
> Fix tree shaking

- package-lock.json
- package.json
- scripts/build-products.js
- src/constants/privateProducts.js
This PR adds a new `isPrivate` prop on the product object. Its value can be `true` or `false` based on whether the product id can be found in the private products ids array. 
When listing a new product, if it's a private one, its id will need to be added to the `privateProducts` file.
> Add isPrivate prop for products based on the private products ids list

- package-lock.json
- package.json
- scripts/build-logos.js
Recently support for filenames without ids was added. The way we checked for ids in filenames was too simple and would break on files which have no id, but do have a dash; like nexus-mutual.svg. This is fixed by adding a simple regex check in two places.
> Fix filename dash bug

- package-lock.json
- package.json
- scripts/build-logos.js
- scripts/build-products.js
- scripts/utils.js
In #87 the output directory of `types.ts` was changed from `dist/logos/types.ts` to `dist/types.ts`. Since this file was previously placed in the `dist/logos` directory, it was copied over to consuming projects which use the `copy-logos.cjs` script. This caused the `types.ts` file to be evaluated by prettier/eslint/etc in ci and sometimes error.
While messing with this, another bug was fixed which caused file extensions to be added to the `LogoFileName` type. But this fix also caused the extension to be removed from the `logo` property of `Product`. Since not all logo's are svg's we need to output the extension too, so the frontends know what file extension to load. This fix eventually got reverted, because it broke logo loading in `frontend-react`.
This pr fixes these issue for good:
- …
> Fix logo names output

- package-lock.json
- package.json
- scripts/build-products.js
We need a `timestamp` prop for products so we can sort them by the newest on FE. We can get this info from the `ProductSet` events block timestamp.
Needed for https://github.com/NexusMutual/frontend-next/issues/359
- got the `timestamp` info from the `ProductSet` events block timestamp
- split the sorting and the mapping of the events data (replaced the `reduce` with a `map` and used a `productMetadata` object) for better readability (introducing the async call made it a bit harder to read)
- used `Promise.all` + `map` rather than a simple `for` loop to get parallel fetching 
- run `npm run build`
- check `generated/products.json` - each product object should have a `timestamp` prop now with the correct date when they were added
> Get timestamp date added data on products objects

- package-lock.json
- package.json
- scripts/build.js
- src/quote/getQuoteAndBuyCoverInputs.test.ts
- src/quote/getQuoteAndBuyCoverInputs.ts
By using `define` in the `tsup` build config we make sure the `process.env.COVER_ROUTER_URL` references get replaced with the value supplied in `.env`. This bundles the string we pass it during buildtime so it doesn't get references during runtime.
> Move COVER_ROUTER_URL from runtime to buildtime

- package-lock.json
- package.json
- src/constants/products.ts
RWA and Coverage should be one category, not two. The categories selector now looks like this:
[Slack context](https://nexusmutual.slack.com/archives/C04JG2C41J4/p1716890979985359)
> Merge RWA and Coverage options in ProductCategoryEnum type

- package-lock.json
- package.json
- src/constants/index.ts
- tsconfig.json
Need to expose `allPrivateProductsIds` so we can use it on other services (i.e. event-scanner)
* export allPrivateProductsIds constant
* built the SDK locally and verified allPrivateProductsIds is now visible 
> feat: Export allPrivateProductsIds constants

- package.json
- scripts/list-product-types.js
- scripts/list-products.js
Add a script to view the productIds and product name on chain. This is useful when updating SDK to ensure we use the correct product data.
The [listing docs](https://www.notion.so/nxmcommunity/Product-Product-Type-Listing-Requests-705a4bdfede842039a968558806741a2) has been updated accordingly to utilise this script as part of the SDK update
* add `list:products` script
* add `list:product-types` script
* manually tested that the script works as intended
> feat: Add list:products / list:product-types scripts

- package.json
- scripts/list-product-types.js
- scripts/list-products.js
Add a script to view the productIds and product name on chain. This is useful when updating SDK to ensure we use the correct product data.
The [listing docs](https://www.notion.so/nxmcommunity/Product-Product-Type-Listing-Requests-705a4bdfede842039a968558806741a2) has been updated accordingly to utilise this script as part of the SDK update
* add `list:products` script
* add `list:product-types` script
* manually tested that the script works as intended
> feat: Add list:products / list:product-types scripts 

- src/constants/products.ts
The `ProductCategoryEnum.All` and `categoryLabelByEnum` `All categories` options have been removed, since they are no longer required for filtering the product categories on the browse covers screen.
- Clean up https://github.com/NexusMutual/frontend-next/pull/836 after getting this live. It now uses inlined copy-pasted versions of `ProductCategoryEnum` and `categoryLabelByEnum`
> chore: remove the 'all' option used for filtering product categories

- package-lock.json
- package.json
- src/constants/products.ts
Enable the `Uncategorized` value in the `ProductCategoryEnum` enum. This ensures that all products have a category, which is helpful for the category selector in the frontend.
Closes #185
> chore: add Uncategorized type to ProductCategoryEnum

- package-lock.json
- package.json
- public/scripts/copy-logos.cjs
Closes  https://github.com/NexusMutual/frontend-react/issues/1656
- update copy logos script to overwrite logos dir files instead of erasing and recreating the dir
- add a new logo file => `npm run build` => `npm link` => go to frontend-react repo => `npm run link @nexusmutual/sdk` => `npm run postinstall` => the new logo should appear in changelog, without any of the other logos removed
> fix(copy-logos): destination files no longer getting deleted

- package-lock.json
- package.json
- public/scripts/copy-logos.cjs
`frontend-next` app has `logos` in gitignore => the copy script cannot find the logos directory to copy the files
- check if logos directory exists first and if not, create it
- 
> fix(copy-logos): check if destination exists if not create it

- package-lock.json
- package.json
- scripts/build-products.js
- src/constants/products.ts
This moved the `ProductTypes` type from the frontend-react project to the sdk. It will be updated automatically when new types are added.
> feat: add ProductTypes type to the sdk

- README.md
- __mocks__/multiformats/cid.ts
- package-lock.json
- package.json
- src/index.ts
- src/ipfs/index.ts
- src/ipfs/uploadIPFSContent.test.ts
- src/ipfs/uploadIPFSContent.ts
- src/ipfs/uploadIPFSData.ts
- src/ipfs/validateIPFSCid.ts
- src/quote/getQuoteAndBuyCoverInputs.test.ts
- src/quote/getQuoteAndBuyCoverInputs.ts
- src/types/index.ts
- src/types/ipfs.ts
This PR adds a new `uploadIPFSContent` util function which takes the content type and content as a json object, validates it, then uploads it to IPFS and outputs the corresponding IPFS hash.
The `getQuoteAndBuyCoverInputs` function has been overloaded to be able to receive ipfs content directly and upload it to IPFS - the previous declaration with `ipfsCid` can still be used.
- call `uploadIPFSContent` with different param values and check the output
- call `getQuoteAndBuyCoverInputs` both overloads and check the output
> feat: ipfs upload utils

- src/ipfs/schemas.ts
- src/ipfs/validateIPFSContent.test.ts
https://nexusmutual.slack.com/archives/C06DJJVEHA4/p1741456274560749
- test validation for wallets ipfs content with decimal amount values
> fix: accept decimal amounts for designated wallets ipfs content

- .github/CONTRIBUTING.md
This PR updates contributing guide commit types description for `perf` and `revert`.
--
> docs: update contributing guide commit types description

- .github/workflows/release-next.yml
- .github/workflows/release.yml
NOTE: [workflow PR](https://github.com/NexusMutual/workflows/pull/7) needs to be merged first
Currently,`release-next` workflow is triggered via PR merged event. This causes the event branch to be the feature branch which causes issues when publishing the `@next` version because only `dev` branch have permission to publish to npm. 
* change event trigger to push on dev branch - this will now make the event branch to be dev
* `build-and-check` job is now skipped if the commits does not trigger a version bump to save resources
added auto SDK latest version bump to the following repos:
* frontend-next
* frontend-react
* cover-router
* event-scanner
* notification-processor
* order-book
* tested in test-ci-1 repo
> ci: fix release-next workflow + add auto SDK version bump PR jobs

- src/constants/privateProducts.js
https://github.com/NexusMutual/sdk/issues/420
--
> fix: set noon defi product as private
